default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>

test:
  <<: *default
  database: rails-mister-cocktail_test

development:
  <<: *default
  database: rails-mister-cocktail_development
